version: "3.3"
services:
  redeye:
    container_name: "PVT"
    build: .
    ports:
      - "8443:8443"
    links:
      - "neo4j:neo4j"
  neo4j:
    image: "neo4j:latest"
    ports:
      - "0.0.0.0:7474:7474"
      - "0.0.0.0:7687:7687"
    env_file:
      - graph.env